### ISSUE TITLE
What was the suggested PR from last meetup?

### ISSUE THREAD

**Issue by misterhtmlcss** [calgary-nodejs/books-api#4]
I'm sorry Polad, but I've been trying to recall the PR that you offered for us to make to the Books API and I'd like to do it, but I can't recall what it was. I ask here, because perhaps I'm not the only one and this saves you repeating yourself.

**Comment by polad** [comment]
@misterhtmlcss I suggested introducing the "refresh token" functionality for cases where a previously authorized user could obtain a new JWT when the current one expires.

Dean Gaudet has proposed a PR this weekend which I reviewed and because I did not have any PRs from other people I decided to merge his PR into the codebase. But you can still offer a PR with your implementation if you like. I can do a code review on that.

**Comment by misterhtmlcss** [comment]
Nice! I didn't see any PRs so I wondered. Thank you for letting me know, if
I get stuck I'll circle back to review the last commit.
